version: "3.9"
services:
  db:
    image: postgres:16
    container_name: fastapi_users_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fastapi_db"]
      interval: 3s
      timeout: 3s
      retries: 10

  app:
    build: .
    container_name: fastapi_users_app
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/fastapi_db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  testdb:
    image: postgres:16
    container_name: fastapi_users_testdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - "5433:5433"
    command: ["postgres", "-p", "5433"]